### ISSUE TITLE
Can't uninstall Fooman SpeedsterAdvanced

### ISSUE THREAD

**Issue by pydubreucq** [fooman/speedsteradvanced#1]
Hi,
I can't uninstall or deactivate Fooman SpeedsterAdvanced.
When I deactivate I have this error:
Fatal error: Class 'Mage_SpeedsterAdvanced_Helper_Data' not found in /home/site/www/app/Mage.php on line 546 
Do you have an idea ?
Best Regards
Pierre-Yves

**Comment by fooman** [comment]
This would indicate that you still have, either some files on the server (possibly in some cache) or some other extension is using some of the extension's functionality (unlikely).

**Comment by pydubreucq** [comment]
Hi,
Thanks a lot.
I've found a php script with fooman link.
Best Regards
