### ISSUE TITLE
Minify doesn't seem to work?

### ISSUE THREAD

**Issue by davidwindell** [fooman/speedsteradvanced#13]
We're running Speedster Advanced on ~5 websites on different platforms but in all cases, the minification doesn't seem to happy.

Everything works fine as far as merging and versioning goes however?

**Comment by surfer190** [comment]
Yeah the minification doesn't work for me either

**Comment by fooman** [comment]
Does it work using the default theme?

**Comment by surfer190** [comment]
No. But it looks like the default theme has been changed from the defualt magento one. Do I need to clear cache and the `/media/js` or `/media/css` folders?

The settings to exclude from minification and merge are there in `developer` -> `Javascript/Css Settings`

**Comment by fooman** [comment]
@surfer190 to troubleshoot if this is an issue with the extension or something else (for example a theme or extension providing javascript that causes a problem when being minified) I would suggest testing our extension on a vanilla install of Magento (no theme, no other extension apart from ours) with your server stack.

**Comment by surfer190** [comment]
@fooman It works. Hmm, the hard part is now finding out why it won't work on this setup. On a side note what package do you recommend to prevent render blocking js above the fold?

**Comment by fooman** [comment]
I don't think there is anything that would be able to automate the above the fold js stuff, at least I haven't come across anything for Magento.

**Comment by davidwindell** [comment]
Fixed, thanks, we were overwriting design_package as you are.
