### ISSUE TITLE
[bug report] when use php7 display error.

### ISSUE THREAD

**Issue by shuaiZend** [fooman/speedsteradvanced#18]
i Click on the tools->Theme Optimiser
display error:
``Fatal error: Uncaught Error: Call to a member function getMetaTitle() on null in /data/wwwroot/website/app/code/core/Mage/Catalog/Block/Product/View.php:56 Stack trace: #0 /data/wwwroot/website/app/code/core/Mage/Core/Block/Abstract.php(297): Mage_Catalog_Block_Product_View->_prepareLayout() #1 /data/wwwroot/website/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout)) #2 /data/wwwroot/website/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('catalog/product...', 'product.info') #3 /data/wwwroot/website/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('catalog/product...', 'product.info') #4 /data/wwwroot/website/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element)) #5 /data/wwwroot/website/app/code/core/Mage/Cor in /data/wwwroot/website/app/code/core/Mage/Catalog/Block/Product/View.php on line 56``
Magento 1.9.3.4
nginx,php-fpm
PHP 7.0.21

**Comment by sprankhub** [comment]
I cannot reproduce this issue.
