### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by sprankhub** [fooman/speedsteradvanced#19]
Hi Kristof,

thanks for this nice extension! Is there any reason why it does not include the minification of HTML? The minify library you use seem to support it, so it seems to be a good fit. Would you merge a PR, which implements this feature?

Cheers
Simon

**Comment by fooman** [comment]
As per our discussion happy to merge this when its ready. Will keep it in the master branch for a while to hopefully get some additional third parties to test out the new functionality.

**Comment by sprankhub** [comment]
Nice, thanks. I implemented it and will send a PR as soon as #22 is merged.

The results are not too good, because the HTML minifier of the minify library insert too many line breaks. I created an issue (https://github.com/mrclay/minify/issues/611) to discuss this. But still, it already saves some KBs and there is no real performance drawback (approx. 0.003ms on the system config admin page, which is quite large).
