### ISSUE TITLE
 Can't configure Fooman Speedster

### ISSUE THREAD

**Issue by pydubreucq** [fooman/speedsteradvanced#2]
Hi,
I've installed Fooman Speedster Advanced but I can't configure it.

I can't go to System > Configuration > Fooman Extensions > Fooman Speedster.
I just have: 
System > Configuration > Fooman Extensions > Assistance
I can't find extension

![fooman_extension](https://cloud.githubusercontent.com/assets/1188199/8496712/aa314884-2177-11e5-8024-fc83ea687796.png)

I've follow the Ultimate Guide.
I've tried with version 0.8.9 like on Magento Connect or with github version (0.8.11)with modman install.

I'm using Magento 1.7 & php 5.4
I saw this extension in System > Configuration > Advanced

Thanks by advance.
Best Regards

**Comment by creatuitydevelopers** [comment]
Look in System > Configuration > Advanced > Developer, where you would find the vanilla Magento combining options for CSS and JS. There will be additional options now.

**Comment by jonathanvaughn** [comment]
Look in System > Configuration > Advanced > Developer, where you would find the vanilla Magento combining options for CSS and JS. There will be additional options now.

**Comment by fooman** [comment]
Hi Jonathan, thanks for jumping in and helping out. Further details are explained in the [manual](http://cdn.fooman.co.nz/media/custom/upload/UserManual-FoomanSpeedsterAdvanced.pdf).
