### ISSUE TITLE
JSON breaks when HTML minification is turned on.

### ISSUE THREAD

**Issue by jishvi** [fooman/speedsteradvanced#24]
After enabling HTML minifications, JSON response breaks its structure. "content-type" in response header was application/json and the response data had some HTML content. I think the module also minified that HTML content too. It was generated using Magento's _toHtml() function.

**Comment by omolto** [comment]
+1

This causes a problem with ajax calls, for example in Manage Categories. It breaks the response and the admin feature can not be used.

We had to disable the HTML minification in order to allow people work.

Best,

**Comment by sprankhub** [comment]
Could you both please test #25 and confirm that it fixes your issue?

**Comment by omolto** [comment]
Hi,

Sorry, it doesn't fix the error on "Manage Categories" page. It still breaks the content.

Best,

**Comment by sprankhub** [comment]
Thanks for your feedback. How can I reproduce the issue? Go on Manage Categories and click on any category? I will check it as soon as I have your feedback.

**Comment by omolto** [comment]
Yes.

Enable the minify feature, go to Manage Categories page and click on any category. After the loading (ajax request) the page breaks.


Best,

**Comment by sprankhub** [comment]
Could you please check my update in #25 again and confirm that this fixes the issue?

**Comment by jishvi** [comment]
Yeah. 
The last update fixed the issue.
