### ISSUE TITLE
HTML minify interferes with API's

### ISSUE THREAD

**Issue by m-overlund** [fooman/speedsteradvanced#29]
When you enable HTML minify, some APIs stop working.
fx we use https://github.com/clerkio/clerk-magento and HTML minify seems to malform the json output through the api.

**Comment by sprankhub** [comment]
Are you already using #27 and #28? If you use both and it still does not work, then Cleark does not set the right content header. But I think they do (https://github.com/clerkio/clerk-magento/blob/1471e599d12fe70fefcc226033e35d1aadb2be3e/code/controllers/ApiController.php#L12), so please apply #28.

**Comment by m-overlund** [comment]
#28 fixed the issue. thanks.
