### ISSUE TITLE
HTML minify issue with comment strings

### ISSUE THREAD

**Issue by m-overlund** [fooman/speedsteradvanced#30]
HTML minify doesn't work for some specific coding styles i guess.
I'm using Magpleasure (Amasty) Blog Pro and when enabled it outputs marks like this - likely because it breaks the html in wrong places.

Which in turn means that the js parts breaks for this module.
`/*      /*]]>*/`

CC: @sprankhub 

![image](https://user-images.githubusercontent.com/504236/47708362-2f00fb80-dc2e-11e8-89de-b29fe1f96321.png)
![image](https://user-images.githubusercontent.com/504236/47708530-8c954800-dc2e-11e8-8f33-3b42d1461359.png)

**Comment by sprankhub** [comment]
Could you post a snippet, which is minified incorrectly? Happy to take a look then.

**Comment by m-overlund** [comment]
The extension provider describes:
`...It necessary to set the work of the minifier, which adds the wrapper /**/ to all scripts. You could see it in the following file: /lib/minify/Minify/HTML.php`


to my best of knowledge this is the part they're referring to:

```
        return $this->_reservePlace($this->_needsCdata($js)
            ? "{$ws1}{$openScript}/*<![CDATA[*/{$js}/*]]>*/</script>{$ws2}"
            : "{$ws1}{$openScript}{$js}</script>{$ws2}"
        );
```
https://github.com/fooman/speedsteradvanced/blob/master/lib/minify/Minify/HTML.php#L239


Incorrectly minified:
```
<div class="mp-selector ng-isolate-scope" mp-name="grid_class" mp-value="w1" mp-options="[{&quot;value&quot;:&quot;w1&quot;,&quot;label&quot;:&quot;Normal&quot;},{&quot;value&quot;:&quot;w2&quot;,&quot;label&quot;:&quot;Smal&quot;},{&quot;value&quot;:&quot;w3&quot;,&quot;label&quot;:&quot;Bred&quot;}]">/*<!--[CDATA[*/<div class="mp-radio-selector grid-class-control"-->



    <table cellpadding="0" cellspacing="0">
        <tbody><tr class="radios">
            <!-- ngRepeat: option in options --><td ng-repeat="option in options" class="ng-scope">

                <input type="radio" name="grid_class_radio" ng-model="radio.value" id="grid_class_radio_w1" value="w1" title="Normal" class="ng-pristine ng-untouched ng-valid">

                <label for="grid_class_radio_w1" title="Normal" class="ng-binding">Normal</label>
            </td><!-- end ngRepeat: option in options --><td ng-repeat="option in options" class="ng-scope">

                <input type="radio" name="grid_class_radio" ng-model="radio.value" id="grid_class_radio_w2" value="w2" title="Smal" class="ng-pristine ng-untouched ng-valid">

                <label for="grid_class_radio_w2" title="Smal" class="ng-binding">Smal</label>
            </td><!-- end ngRepeat: option in options --><td ng-repeat="option in options" class="ng-scope">

                <input type="radio" name="grid_class_radio" ng-model="radio.value" id="grid_class_radio_w3" value="w3" title="Bred" class="ng-pristine ng-untouched ng-valid">

                <label for="grid_class_radio_w3" title="Bred" class="ng-binding">Bred</label>
            </td><!-- end ngRepeat: option in options -->
        </tr>
        <tr class="selectors">
            <!-- ngRepeat: option in options --><td ng-repeat="option in options" ng-click="setValue(option.value)" class="ng-scope">
                <div class="option w1" title="Normal">&nbsp;</div>
            </td><!-- end ngRepeat: option in options --><td ng-repeat="option in options" ng-click="setValue(option.value)" class="ng-scope">
                <div class="option w2" title="Smal">&nbsp;</div>
            </td><!-- end ngRepeat: option in options --><td ng-repeat="option in options" ng-click="setValue(option.value)" class="ng-scope">
                <div class="option w3" title="Bred">&nbsp;</div>
            </td><!-- end ngRepeat: option in options -->
        </tr>
    </tbody></table>

    <div class="mockup w1">
        <div class="fake-element thumbnail big-margin"></div>
        <div class="fake-element title big-margin"></div>
        <div class="fake-element line small-margin"></div>
        <div class="fake-element line small-margin"></div>
        <div class="fake-element line big-margin"></div>
        <div class="fake-element button"></div>
    </div>




<input type="hidden" name="grid_class" value="w1">/*]]&gt;*/</div>
```

**Comment by sprankhub** [comment]
This looks quite... Specific ;-) They do not even use valid HTML.

Not sure if/when I will be able to check that in detail. Until then, I suggest you to only use the HTML minification in the frontend. The following code in your custom module should work:

    <config>
        <global>
            <events>
                <http_response_send_before>
                    <observers>
                        <speedsterAdvanced>
                            <type>disabled</type>
                        </speedsterAdvanced>
                    </observers>
                </http_response_send_before>
            </events>
        </global>
        <frontend>
            <events>
                <http_response_send_before>
                    <observers>
                        <speedsterAdvanced>
                            <class>speedsterAdvanced/observer</class>
                            <method>httpResponseSendBefore</method>
                        </speedsterAdvanced>
                    </observers>
                </http_response_send_before>
            </events>
        </frontend>
    </config>

**Comment by fooman** [comment]
Closing this as it's very specific as @sprankhub mentioned, with a workaround provided.
