### ISSUE TITLE
Doesn;t seem to be working for me.

### ISSUE THREAD

**Issue by coolocean** [fooman/speedsteradvanced#4]
Hi,

I have installed speedster advanced. However It doesn't seem to minify the js and css. 

I am on 1.9.1. What can you suggest to make it working? Or should I go for your standard version?

url: www.buyrudraksha.com

**Comment by fooman** [comment]
It does work - these files are merged and minified:

```
<link rel="stylesheet" type="text/css" href="http://media.buyrudraksha.com/media/css/4d54d828b02a714c4801cd8de1fa6ef3-1-1430358972.css" />
<link rel="stylesheet" type="text/css" href="http://media.buyrudraksha.com/media/css/69b04e834b4ecbbf21cedd04ad79e408-1-1436496235.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://media.buyrudraksha.com/media/css/6d86b4ed9b1426a167a36115d822bceb-1-1422847121.css" media="print" />
<script type="text/javascript" src="http://media.buyrudraksha.com/media/js/3b05f7d1d2824967e79b09fd5bf8b76c-1430358972.js"></script>
<script type="text/javascript" src="http://media.buyrudraksha.com/media/js/60ab8c1a0e8223dbc526d4ce05609120-1436496343.js"></script>
```

All other files not included were not loaded the Magento way (by including them a xml layout update) and are therefore not covered by this extension. Suggest to get in touch with the developers of your theme.

**Comment by coolocean** [comment]
Thank you then I'll check with the theme dev on this.
