### ISSUE TITLE
Speedster Advanced not listed among installed extensions

### ISSUE THREAD

**Issue by sasoriza** [fooman/speedsteradvanced#5]
Fooman Common will not recognize Speedster Advanced. Email Attachments is listed correctly as installed, but not Speedster Advanced, however Speedster is running.

**Comment by fooman** [comment]
Apologies M1 work hasn't really been a priority for us hence the delay - but v0.8.14 should now show the version number if Fooman Common is present. There is no selftest.

**Comment by sasoriza** [comment]
Just wanted to confirm that it is now listed.
