### ISSUE TITLE
Tag current master release

### ISSUE THREAD

**Issue by ajbonner** [fooman/speedsteradvanced#8]
Hi there,

Thanks so much for this project, it's helped our deployment process immeasurably. 

As we're using composer to pull this in, it would be nice to have the current master version tagged so we can depend on a hard version rather than dev-master.

We can always put a dev-master#gitref in there too, but a tag is nicer.

Thank you again for releasing this!
Aaron.

**Comment by fooman** [comment]
I have just pushed a few versions to here which came with tags (latest currently v0.8.14). Apologies that this took a while - M2 is keeping me busy.
