### ISSUE TITLE
Minified CSS - IE8 & 9 Issue

### ISSUE THREAD

**Issue by LauraCarr87** [fooman/speedsteradvanced#9]
Hi,

I am using a theme for Magento which I believe uses your plugin.  However when I  turn on the compressed CSS - it causes a display issue in IE 8 & 9 which I think is related to the large amount of css in one file. Apparently there is a IE issue which older versions don't render CSS in a file after it's read 4095 selectors, and I think this could be what's happening when your plugin merges the file. Is it possible to split the CSS for IE 8/9 or turn off the compilation for just these browsers?

Thanks
Laura

**Comment by fooman** [comment]
Please get in touch with the authors of the theme as I can't provide support for it. Turning off compilation based on browser is not something that is possible.
